version: 3

includes:
  generator:
    taskfile: generator/Taskfile.yaml
    dir: generator
  cli:
    taskfile: cli/Taskfile.yaml
    dir: cli
  website:
    taskfile: website/Taskfile.yaml
    dir: website

tasks:
  publish:
    deps:
      - generator:check
    cmds:
      - task: cli:publish

  deploy:
    deps:
      - generator:check
    cmds:
      - task: website:deploy
