version: 3

includes:
  generator:
    taskfile: packages/generator/Taskfile.yaml
    dir: packages/generator
  cli:
    taskfile: packages/cli/Taskfile.yaml
    dir: packages/cli
  website:
    taskfile: packages/website/Taskfile.yaml
    dir: packages/website
  hono:
    taskfile: packages/hono/Taskfile.yaml
    dir: packages/hono

tasks:
  check:
    deps:
      - generator:check
      - cli:check
      - website:check
      - hono:check

  publish:
    deps:
      - generator:check
    cmds:
      - task: cli:publish

  deploy:
    deps:
      - generator:check
    cmds:
      - task: website:deploy

  release:
    deps:
      - publish
      - deploy
