version: 3

includes:
  common:
    taskfile: ../../Taskfile.common.yaml
    flatten: true

tasks:
  build:
    cmds:
      - rm -rf dist/
      - bun tsc --p tsconfig.publish.json
#      - bun ts-hack.ts dist/
      - find dist/ -type f -name "*.js" -exec perl -pi -e 's/from "(\..+?)"/from "\1.js"/g' {} +
