version: 3

includes:
  common:
    taskfile: ../Taskfile.common.yaml
    flatten: true

tasks:
  build:
    deps:
      - types
      - lint
      - test
    cmds:
      - rm -rf dist/
      - bun build src/bin.ts --outdir=dist/ --packages=external --target=node --sourcemap=external --format=esm
    sources:
      - ../generator/src/**/*
      - src/**/*
      - ../bun.lockb
    generates:
      - dist/**/*

  publish:
    deps:
      - build
    cmd: npm publish
    sources:
      - dist/**/*
      - package.json
